function getAnnualMileage(ANNUAL_MILEAGE) {
  let ANNUAL_MILEAGE_RESPONSE;
  if(1000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '199';
  }
  else if(2000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '200';
  }
  else if(3000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '201';
  }
  else if(4000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '202';
  }
  else if(5000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '203';
  }
  else if(6000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '204';
  }
  else if(7000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '205';
  }
  else if(8000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '206';
  }
  else if(9000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '207';
  }
  else if(10000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '208';
  }
  else if(11000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '209';
  }
  else if(12000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '210';
  }
  else if(13000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '211';
  }
  else if(14000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '212';
  }
  else if(15000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '213';
  }
  else if(16000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '214';
  }
  else if(17000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '215';
  }
  else if(18000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '216';
  }
  else if(19000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '217';
  }
  else if(20000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '218';
  }
  else if(21000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '219';
  }
  else if(22000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '220';
  }
  else if(23000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '221';
  }
  else if(24000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '222';
  }
  else if(25000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '223';
  }
  else if(30000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '224';
  }
  else if(50000 >= ANNUAL_MILEAGE) {
    ANNUAL_MILEAGE_RESPONSE = '225';
  }
  else {
    ANNUAL_MILEAGE_RESPONSE = '226';
  }
  return ANNUAL_MILEAGE_RESPONSE;
}

module.exports = getAnnualMileage;