function getDrivingLicenseNoClaims(DRIVING_LICENSE_NO_CLAIMS, DRIVING_LICENSE_NO_CLAIMS_OPTIONS) {
  let DRIVING_LICENSE_NO_CLAIMS_RESPONSE;
  if (DRIVING_LICENSE_NO_CLAIMS.toUpperCase() == 'N') {
    DRIVING_LICENSE_NO_CLAIMS_RESPONSE = DRIVING_LICENSE_NO_CLAIMS_OPTIONS[0].value;
  } else if (1 == Number(DRIVING_LICENSE_NO_CLAIMS)) {
    DRIVING_LICENSE_NO_CLAIMS_RESPONSE = DRIVING_LICENSE_NO_CLAIMS_OPTIONS[1].value;
  } else if (20 >= Number(DRIVING_LICENSE_NO_CLAIMS)) {
    DRIVING_LICENSE_NO_CLAIMS_RESPONSE = DRIVING_LICENSE_NO_CLAIMS_OPTIONS[
      DRIVING_LICENSE_NO_CLAIMS_OPTIONS.length - 1
    ].value;
  } else {
    DRIVING_LICENSE_NO_CLAIMS = Number(DRIVING_LICENSE_NO_CLAIMS);
    for (let i = 2; i < DRIVING_LICENSE_NO_CLAIMS_OPTIONS.length - 1; i++) {
      const DRIVING_LICENSE_NO_CLAIMS_OPTION = DRIVING_LICENSE_NO_CLAIMS_OPTIONS[i];
      const DRIVING_LICENSE_NO_CLAIMS_OPTION_LABEL = Number(
        DRIVING_LICENSE_NO_CLAIMS_OPTION.label.replace('years', '').trim()
      );
      if (DRIVING_LICENSE_NO_CLAIMS == DRIVING_LICENSE_NO_CLAIMS_OPTION_LABEL) {
        DRIVING_LICENSE_NO_CLAIMS_RESPONSE = DRIVING_LICENSE_NO_CLAIMS_OPTION.value;
        break;
      }
    }
  }

  return DRIVING_LICENSE_NO_CLAIMS_RESPONSE;
}

module.exports = getDrivingLicenseNoClaims;