function getOvernightStorage(OVERNIGHT_STORAGE, OVERNIGHT_STORAGE_OPTIONS) {
  let OVERNIGHT_STORAGE_RESPONSE;
  OVERNIGHT_STORAGE = OVERNIGHT_STORAGE.toLowerCase();
  if (OVERNIGHT_STORAGE.includes('driveway')) {
    OVERNIGHT_STORAGE_RESPONSE = OVERNIGHT_STORAGE_OPTIONS[0].value;
  } else if (OVERNIGHT_STORAGE.includes('home' || 'road')) {
    OVERNIGHT_STORAGE_RESPONSE = OVERNIGHT_STORAGE_OPTIONS[1].value;
  } else if (OVERNIGHT_STORAGE.includes('garage')) {
    OVERNIGHT_STORAGE_RESPONSE = OVERNIGHT_STORAGE_OPTIONS[2].value;
  } else {
    OVERNIGHT_STORAGE_RESPONSE = OVERNIGHT_STORAGE_OPTIONS[3].value;
  }

  return OVERNIGHT_STORAGE_RESPONSE;
}

module.exports = getOvernightStorage;