function getVoluntaryExcess(COVER_TYPE, VOLUNTARY_EXCESS, VOLUNTARY_EXCESS_OPTIONS) {
  let VOLUNTARY_EXCESS_RESPONSE;
  if (COVER_TYPE.includes('comprehensive')) {
    if (VOLUNTARY_EXCESS >= 0 && VOLUNTARY_EXCESS <= 49) {
      VOLUNTARY_EXCESS_RESPONSE = VOLUNTARY_EXCESS_OPTIONS[0];
    }
    else if (VOLUNTARY_EXCESS >= 50 && VOLUNTARY_EXCESS <= 174) {
      VOLUNTARY_EXCESS_RESPONSE = VOLUNTARY_EXCESS_OPTIONS[1];
    }
    else if (VOLUNTARY_EXCESS >= 175 && VOLUNTARY_EXCESS <= 374) {
      VOLUNTARY_EXCESS_RESPONSE = VOLUNTARY_EXCESS_OPTIONS[2];
    }
    else if (VOLUNTARY_EXCESS >= 375) {
      VOLUNTARY_EXCESS_RESPONSE = VOLUNTARY_EXCESS_OPTIONS[3];
    }
  }
  else {
    VOLUNTARY_EXCESS_RESPONSE = VOLUNTARY_EXCESS_OPTIONS[0];
  }

  return VOLUNTARY_EXCESS_RESPONSE;
}

module.exports = getVoluntaryExcess;